### PR TITLE
Finished PS7

### PR DESCRIPTION
**Pull request by jfan3**
Hi Professor Evans!

Sorry it's me again... In doing the transition path for population, do we need to solve for eigenvector and eigenvalue each time? If not, how do we calculate g_{n, t+1} again?

Thanks!

Fiona

### CODE REVIEW

**Comment by rickecon** [comment]
Yes. You can submit PS7 (Ex 10.1, 10.2, 10.3, 10.4) anytime between now and next Wednesday. However, PS8 (Ex. 10.5, 10.6) is due next Wednesday also, so make sure to pace yourself.

**Comment by rickecon** [comment]
@jfan3 @SophiaMo. Here are some lines of code from my function. You can see where I build my `OMEGA` matrix out of fertility, mortality, and immigration rates. Then you see where I solve for the steady-state using `np.linalg.eig()`. I then make sure to get the real parts.
```python
fert_rates = get_fert(E + S, min_yr, max_yr, graph=False)
mort_rates, infmort_rate = get_mort(E + S, min_yr, max_yr,
                                    graph=False)
mort_rates_S = mort_rates[-S:]
imm_rates_orig = get_imm_resid(E + S, min_yr, max_yr, graph=False)
OMEGA_orig = np.zeros((E + S, E + S))
OMEGA_orig[0, :] = \
    ((1 - infmort_rate) * fert_rates +
     np.hstack((imm_rates_orig[0], np.zeros(E + S - 1))))
OMEGA_orig[1:, :-1] += np.diag(1 - mort_rates[:-1])
OMEGA_orig[1:, 1:] += np.diag(imm_rates_orig[1:])

# Solve for steady-state population growth rate and steady-state
# population distribution by age using eigenvalue and eigenvector
# decomposition
eigvalues, eigvectors = np.linalg.eig(OMEGA_orig)
g_n_SS = (eigvalues[np.isreal(eigvalues)].real).max() - 1
eigvec_raw = \
    eigvectors[:,
               (eigvalues[np.isreal(eigvalues)].real).argmax()].real
omega_SS_orig = eigvec_raw / eigvec_raw.sum()
```

**Comment by rickecon** [comment]
My code above is for the steady-state population growth rate `gbar_n` and ergodic stationary population distribution `omegahat_s`. To find the time path of `gtilde_{n,t}` and the time path of `omegahat_{s,t}`, you have to:

1. Start with an initial distribution `omega_{s,0}` for all `s`. It doesn't matter if it is stationary or nonstationary.
2. Use `OMEGA` matrix to generate nonstationary `omega_{s,1}` for all `s`.
  * You can stationarize `omega_{s,1}` by dividing by the total population `omegahat_{s,1} = omega_{s,1} / sum(omega_1)`.
  * The growth rate from period 0 to period 1 is `g_{n,1} = sum(omega_1) / sum(omega_0) - 1`.
3. Repeat this until you have arrived at the steady-state at period `T`.

**Comment by jfan3** [comment]
Thanks Professor Evans!

I actually got it working but forgot to submit it today... I will put together the write-up submit it later today!

**Comment by rickecon** [comment]
@jfan3. 4(b) and 4(c) don't look right. But I am happy to move on if you want to.

**Comment by jfan3** [comment]
Sorry I'll take a hard look at them tomorrow!

**Comment by jfan3** [comment]
All done!

**Pull request merged**
